export const GET_CURRENT_WEATHER_REQUEST = 'GET_CURRENT_WEATHER_REQUEST';
export const GET_CURRENT_WEATHER_SUCCESS = 'GET_CURRENT_WEATHER_SUCCESS';
export const GET_CURRENT_WEATHER_FAILURE = 'GET_CURRENT_WEATHER_FAILURE';

export const CHANGE_CITY_REQUEST = "CHANGE_CITY_REQUEST";

export const GET_OTHER_DAYS_REQUEST = 'GET_OTHER_DAYS_REQUEST';
export const GET_OTHER_DAYS_SUCCESS = 'GET_OTHER_DAYS_SUCCESS';
export const GET_OTHER_DAYS_FAILURE = 'GET_OTHER_DAYS_FAILURE';